version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: on-failure
    network_mode: host

  relay:
    image: gbrlanrd/relay:latest
    ports:
      - "8090:8090"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@localhost:27017/
      - SPRING_RABBITMQ_HOST=localhost  
    network_mode: host

  consumer:
    image: gbrlanrd/consumer:latest
    ports:
      - "8091:8091"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
      - relay
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@localhost:27017/
      - SPRING_RABBITMQ_HOST=localhost  
    network_mode: host

  mongodb:
    image: mongo:4.4.3
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=component-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./mongod/config/mongod.conf:/etc/mongod.conf

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-volume:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    # links:
    #   - prometheus:prometheus
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
    network_mode: host

volumes:
  prometheus-volume:
  grafana-volume: