version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5670:5672"
    restart: on-failure
    network_mode: host

  relay:
    image: gbrlanrd/relay:latest
    ports:
      - "8090:8090"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://camarguinho:camarguinho@localhost:27017/
      - SPRING_RABBITMQ_HOST=localhost  
    network_mode: host

  consumer:
    image: gbrlanrd/consumer:latest
    ports:
      - "8091:8091"
    restart: on-failure
    depends_on:
      - rabbitmq
      - mongodb
      - relay
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://camarguinho:camarguinho@localhost:27017/
      - SPRING_RABBITMQ_HOST=localhost  
    network_mode: host

  mongodb:
    image: mongo:4.4.3
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=component-db
      - MONGO_INITDB_ROOT_USERNAME=camarguinho
      - MONGO_INITDB_ROOT_PASSWORD=camarguinho
    ports:
      - "27017:27017"
    volumes:
      - ./mongod/config/mongod.conf:/etc/mongod.conf