spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://camarguinho:camarguinho@localhost:27017/}
      database: component-db
      authentication-database: admin
  rabbitmq:
    port: 5672
    host: ${SPRING_RABBITMQ_HOST:localhost}
    username: guest
    password: guest
    queue: component-zone
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8090
  error:
    include-message: always

jwt:
  secret: littlesecret
  expiration: 600000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
